[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rand = "0.8.5"
toml = "0.8.1"

[build-dependencies]
glob = "0.3.1"

[[bin]]
name = "1_hello_world"
path = "src/bin/1. Getting Started/hello_world.rs"

[[bin]]
name = "2_main"
path = "src/bin/2. Guessing Game/main.rs"

[[bin]]
name = "3_data_types"
path = "src/bin/3. Common Programming Concepts/data_types.rs"

[[bin]]
name = "3_variables_and_mutability"
path = "src/bin/3. Common Programming Concepts/variables_and_mutability.rs"

