[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "build.rs"

[dependencies]
glob = "0.3.1"

[build-dependencies]
glob = "0.3.1"
